### ISSUE TITLE
Add battery filtering to jenkins plugin

### ISSUE THREAD

**Issue by lukzeg** [jenkinsci/open-stf-plugin#11]
The pull request :
https://github.com/jenkinsci/open-stf-plugin/pull/10

Contains changes needed to filter Android devices via battery level.

**Comment by justice3120** [comment]
Hi, @lukzeg 
I released that as ver 1.0.6.
Thanks to your contributing!!

**Comment by lukzeg** [comment]
Hi, @justice3120,

Thank you for giving me a chance to add this small future to your plugin. 
BR,
Lukas
