### ISSUE TITLE
Support android-emulator version:3.0

### ISSUE THREAD

**Issue by hram** [jenkinsci/open-stf-plugin#12]
I had error with android-emulator version:3.0
FATAL: hudson.plugins.android_emulator.util.Utils.discoverAndroidHome(Lhudson/Launcher;Lhudson/model/Node;Lhudson/EnvVars;Ljava/lang/String;)Ljava/lang/String;
java.lang.NoSuchMethodError: hudson.plugins.android_emulator.util.Utils.discoverAndroidHome(Lhudson/Launcher;Lhudson/model/Node;Lhudson/EnvVars;Ljava/lang/String;)Ljava/lang/String;
	at hudson.plugins.openstf.STFBuildWrapper.setUp(STFBuildWrapper.java:121)
	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)

**Comment by lukzeg** [comment]
@hram ,

I noticed the same problems as you. I created a fix for it which I tested on latest STF ver.

@justice3120 I will be grateful if you will find a second to look at my changes.

**Comment by justice3120** [comment]
@hram 
I released https://github.com/jenkinsci/open-stf-plugin/pull/14 as version 1.0.7.

@lukzeg Thanks!

**Comment by hram** [comment]
@justice3120 I do not see 1.0.7 https://wiki.jenkins.io/display/JENKINS/Open+STF+Plugin

**Comment by lukzeg** [comment]
Hi @hram,

Mostly looks like the page is not updated as I'm able to see new ver 1.0.7 under my jenkins(
![v_1_0_7](https://user-images.githubusercontent.com/22797365/35199883-b09e09d6-fefc-11e7-9c94-331a6678a0bb.png)
)

Also under http://updates.jenkins-ci.org/download/plugins/open-stf/ we can see released ver. Thats is a great news, a specially for me, as one client wants only use release ver.

I have hope that @justice3120  will find a second to update the jenkins page with latest informations, as you have right. Lack of this info about latest update can be confusing for other people.
