### ISSUE TITLE
STF farm changes lead to NullPointerException 

### ISSUE THREAD

**Issue by sbmehdy** [jenkinsci/open-stf-plugin#19]
Hi,
Using the STF plugin connected to a farm which has its devices changing constantly, builds work only when the saved state of the farm has not changed (i.e. if we don't add/remove phones over time).

Otherwise, we run into this issue when the job runs:
```
15:07:33 | FATAL: null
15:07:33 | java.lang.NullPointerException
15:07:33 | 	at hudson.plugins.openstf.util.Utils.expandVariables(Utils.java:55)
15:07:33 | 	at hudson.plugins.openstf.STFBuildWrapper.setUp(STFBuildWrapper.java:100)
15:07:33 | 	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
15:07:33 | 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
15:07:33 | 	at hudson.model.Run.execute(Run.java:1794)
15:07:33 | 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
15:07:33 | 	at hudson.model.ResourceController.execute(ResourceController.java:97)
15:07:33 | 	at hudson.model.Executor.run(Executor.java:429)
```

Which goes away once configuring the job and refreshing the list of devices.
Can this be done at runtime (list of devices + regexp filter) ?

Jenkins: Latest 2.125, 
JDK: 1.8,
O.S: MacOs 10.13.4
Plugin version: latest, 1.0.8

**Comment by lukzeg** [comment]
Hi @sbmehdy,
I will look at this problem. I'm not sure if this is possible. I need to investigate this issue/ feature.

**Comment by justice3120** [comment]
👀

**Comment by justice3120** [comment]
Hi @sbmehdy,
Does this always occur if a device is deleted / added after job setting?

This seemed not to happen if I used the mock STF server, changed the contents of the device list after job setup, and executed the job.

**Comment by sbmehdy** [comment]
In our case, it does seem to occur every time one removes at least one device.
Is your content list populated with unavailable devices too ? 
It seems like if one removes a device and adds another, the STF farm keeps the device in its list (with the attribute _present_ toggled to false) and it might be the root cause of this.

Have you tried setting the project, then mocking one additional unavailable device, and trying to run the job again?

**Comment by sbmehdy** [comment]
I haven't been able to reproduce the bug yet, and I have tried the following:
- I initially tried to set up two devices on the farm, then the job, then ran tests. OK ✅ 
- Removed one of the two devices (so one device connected, and one made unavailable by unplugging), ran the tests without changing the job config. OK ✅ 
- I added a third device, and removed the previously available one (so two unavailable, one new), didn't change job config and ran tests. OK ✅ 
- I tried removing all devices (leaving only devices "disconnected" in the list) and had no issues either ✅.

However, coming back from the weekend (where no job ran but all computers stayed up and all services are still running), I notice that the issue happens again. 
Logs on the STF farm indicate no attempt at a connection, so I assume it has everything to do with something on Jenkins itself.

I'm not quite sure what else I could help with in terms of debugging but if you have any ideas at this point, let me know.

**Comment by lukzeg** [comment]
Hi @shmehdy,

I would like to apologise to you for a silence from my site. Your pieces of information are really helpful for me.
From looking at the code, mostly looks like during creating the build, we are receiving Null from device condition ( regex which you set to filter devices).
I compiling right now simple build to make some debug logs for device conditions, which might show us, what is happening.
Will you be able to apply this debug plugin on your farm, and if the bug will appear, share with my output? So we will might to apply the patch on our side(maybe refactor applying conditions) or create a bug on Jenkins.

KR,
Lukas Z

**Comment by sbmehdy** [comment]
@lukzeg Happy to help anytime. As soon as the build is available, I can try it out on our setup.

I should add that I've tried to let the job pull any device without adding any filter (no regexp) and the bug occurs the same way still.

**Comment by lukzeg** [comment]
Hi @sbmehdy ,

During few seconds of tests on my local machine, I was also available to reproduce this issue.
Are you running your Jenkins as docker container? As I'm always receiving this issue when I'm restarting my Jenkins machine. 

I will dig around this problem tomorrow.

KR,
Lucas

**Comment by sbmehdy** [comment]
Hi @lukzeg,
I'm not running Jenkins within Docker. I do have Docker installed on the Mac Mini running Jenkins, but I'm purely starting it using the JVM, using the following Automator (mostly GC settings passed to the JVM, nothing out of the ordinary):

```
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export PATH=/usr/bin:/usr/bin/local:$PATH
/usr/bin/java -Dmail.smtp.starttls.enable=true -server -Xms8g -Xmx8g -XX:+AlwaysPreTouch -Xloggc:$JENKINS_HOME/gc-%t.log -XX:NumberOfGCLogFiles=5 -XX:+UseGCLogFileRotation -XX:GCLogFileSize=20m -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC -XX:+PrintAdaptiveSizePolicy -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1 -jar /usr/local/opt/jenkins/libexec/jenkins.war --httpListenAddress=0.0.0.0 --httpPort=8080
```

The computer on which it is running is kept active (does not sleep) thanks to the Amphetamine app. Disks do not go inactive either (disabled that setting on our MacOS). 

So far the only time I've really observed that behaviour seems to be after a long-ish period of inactivity (i.e. after a weekend). Narrowing down the issue still seems tricky, but always happy to help.

**Comment by sbmehdy** [comment]
@lukzeg 
I just tried restarting Jenkins (jenkins_url/restart) and can confirm that the problem is happening post-restart !!
Looks like you were on to something 👍

**Comment by justice3120** [comment]
Hi @lukzeg

I examined it for a while.

Jenkins version 2.7.4, plugin version 1.0.7 in combination, it seemed that this problem did not occur when restarting Jenkins.
However, when running on Jenkins version 2.7.4, plugin version 1.0.8, this problem seemed to happen.

So, it seems that the code change when upgrading the plugin to version 1.0.8 is causing this problem, I think.

**Comment by lukzeg** [comment]
Hi @sbmehdy , @justice3120 ,

I will try to setup today small test farm on my machine. If you will have time, can you look at this build? And confirm that everything works? From the quick debug check everything looks okay, but any comments will be helpful.
[open-stf.zip](https://github.com/jenkinsci/open-stf-plugin/files/2094777/open-stf.zip)

KR, 
Lukas

**Comment by lukzeg** [comment]
I tested on my machine latest local debug build(
[open-stf.zip](https://github.com/jenkinsci/open-stf-plugin/files/2097768/open-stf.zip)
) and works okay for me. 
Later in evening, I will fix tests, to fit new implementation. I have hope that today I will finish implementation and I will create PR.
@justice3120 : Thank you for checking it. This information was really useful.

KR,
Lukas

**Comment by sbmehdy** [comment]
@lukzeg 
I have installed the version you provided and tried to run the job again (post-restart), and I get the following:
```
10:32:28 | FATAL: null object
10:32:28 | net.sf.json.JSONException: null object
10:32:28 | 	at net.sf.json.JSONObject.verifyIsNull(JSONObject.java:2688)
10:32:28 | 	at net.sf.json.JSONObject.keys(JSONObject.java:2092)
10:32:28 | 	at hudson.plugins.openstf.util.Utils.expandVariables(Utils.java:55)
10:32:28 | 	at hudson.plugins.openstf.STFBuildWrapper.setUp(STFBuildWrapper.java:100)
10:32:28 | 	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
10:32:28 | 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
10:32:28 | 	at hudson.model.Run.execute(Run.java:1798)
10:32:28 | 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
10:32:28 | 	at hudson.model.ResourceController.execute(ResourceController.java:97)
10:32:28 | 	at hudson.model.Executor.run(Executor.java:429)
```

Nothing more than that, but I hope that helps.
I can confirm that post-restart the job systematically fails.

**Comment by justice3120** [comment]
Hi @sbmehdy

We released the fix as vwe 1.0.9.
But,  this includes incompatible changes, I think you need to reconfigure the build settings.

**Comment by sbmehdy** [comment]
Hey @justice3120 , thank you for your help!
I tried setting things up, running a job (worked) then restarting and running the job.. and it worked. So it looks like that is fixed, thank you!

**Comment by SwirMix** [comment]
Hello!
We install OpenSTF (1.0.9) plugin on our jenkins CI (2.164.3) and see this problem.
Our farm is active. (When we create job, all device active)

FATAL: null
java.lang.NullPointerException
	at hudson.plugins.openstf.STFBuildWrapper.setUp(STFBuildWrapper.java:147)
	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1816)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE 

jdk 1.8
Ubuntu 18.04

**Comment by justice3120** [comment]
👀
